export const FALLBACK_REPOS = [
  {
    name: "portfolio-terrain",
    fullName: "AlistairBishop06/portfolio-terrain",
    description: "A 3D GitHub portfolio terrain.",
    language: "JavaScript",
    htmlUrl: "https://github.com/AlistairBishop06/portfolio-terrain",
    stars: 0,
    forks: 0,
    updatedAt: "2026-06-06T14:37:58Z",
    pushedAt: "2026-06-06T14:37:54Z",
    size: 13,
    defaultBranch: "main",
    commitCount: 1
  },
  {
    name: "Shift-System",
    fullName: "AlistairBishop06/Shift-System",
    description: "A shift planning system.",
    language: "TypeScript",
    htmlUrl: "https://github.com/AlistairBishop06/Shift-System",
    stars: 0,
    forks: 0,
    updatedAt: "2026-06-06T14:23:10Z",
    pushedAt: "2026-06-06T14:23:07Z",
    size: 855,
    defaultBranch: "main",
    commitCount: 9
  },
  {
    name: "Youtube-Keyword-Scraper",
    fullName: "AlistairBishop06/Youtube-Keyword-Scraper",
    description: "Python tooling for YouTube keyword scraping.",
    language: "Python",
    htmlUrl: "https://github.com/AlistairBishop06/Youtube-Keyword-Scraper",
    stars: 0,
    forks: 0,
    updatedAt: "2026-06-06T12:54:12Z",
    pushedAt: "2026-06-06T12:54:08Z",
    size: 10,
    defaultBranch: "main",
    commitCount: 32
  },
  {
    name: "alistairbishop06.github.io",
    fullName: "AlistairBishop06/alistairbishop06.github.io",
    description: "A first-person browser-based 3D library where each book represents a GitHub repository.",
    language: "JavaScript",
    htmlUrl: "https://github.com/AlistairBishop06/alistairbishop06.github.io",
    stars: 0,
    forks: 0,
    updatedAt: "2026-06-05T21:48:43Z",
    pushedAt: "2026-06-05T21:48:39Z",
    size: 334,
    defaultBranch: "main",
    commitCount: 38
  },
  {
    name: "Universe-Explorer-Web-App",
    fullName: "AlistairBishop06/Universe-Explorer-Web-App",
    description: "A universe exploration web app.",
    language: "C++",
    htmlUrl: "https://github.com/AlistairBishop06/Universe-Explorer-Web-App",
    stars: 0,
    forks: 0,
    updatedAt: "2026-06-01T15:49:36Z",
    pushedAt: "2026-06-01T15:20:12Z",
    size: 72,
    defaultBranch: "main",
    commitCount: 3
  },
  {
    name: "Idea-Ranker",
    fullName: "AlistairBishop06/Idea-Ranker",
    description: "A Python idea ranking tool.",
    language: "Python",
    htmlUrl: "https://github.com/AlistairBishop06/Idea-Ranker",
    stars: 0,
    forks: 0,
    updatedAt: "2026-05-27T14:32:01Z",
    pushedAt: "2026-05-27T14:30:37Z",
    size: 1,
    defaultBranch: "main",
    commitCount: 1
  },
  {
    name: "Chaos-Chess",
    fullName: "AlistairBishop06/Chaos-Chess",
    description: "Browser-based multiplayer chess variant with rule cards.",
    language: "JavaScript",
    htmlUrl: "https://github.com/AlistairBishop06/Chaos-Chess",
    stars: 1,
    forks: 0,
    updatedAt: "2026-05-24T14:15:28Z",
    pushedAt: "2026-05-24T14:15:25Z",
    size: 12280,
    defaultBranch: "main",
    commitCount: 68
  },
  {
    name: "Mario64-Physics-Extraction",
    fullName: "AlistairBishop06/Mario64-Physics-Extraction",
    description: "C++ extraction experiments for Mario 64-style physics.",
    language: "C++",
    htmlUrl: "https://github.com/AlistairBishop06/Mario64-Physics-Extraction",
    stars: 0,
    forks: 0,
    updatedAt: "2026-05-18T15:34:18Z",
    pushedAt: "2026-05-18T15:34:14Z",
    size: 2497,
    defaultBranch: "main",
    commitCount: 9
  },
  {
    name: "FIXRBot",
    fullName: "AlistairBishop06/FIXRBot",
    description: "Lightweight Node.js monitor for FIXR ticket availability with email notifications.",
    language: "JavaScript",
    htmlUrl: "https://github.com/AlistairBishop06/FIXRBot",
    stars: 0,
    forks: 0,
    updatedAt: "2026-05-13T19:38:57Z",
    pushedAt: "2026-05-13T19:37:40Z",
    size: 17,
    defaultBranch: "main",
    commitCount: 5
  },
  {
    name: "WikiWalk",
    fullName: "AlistairBishop06/WikiWalk",
    description: "A Python Wikipedia walking project.",
    language: "Python",
    htmlUrl: "https://github.com/AlistairBishop06/WikiWalk",
    stars: 0,
    forks: 0,
    updatedAt: "2026-05-11T15:38:00Z",
    pushedAt: "2026-05-11T15:25:43Z",
    size: 14,
    defaultBranch: "main",
    commitCount: 1
  },
  {
    name: "World-Generator-and-Explorer",
    fullName: "AlistairBishop06/World-Generator-and-Explorer",
    description: "A browser-based procedural terrain editor and explorer built with JavaScript and Three.js.",
    language: "HTML",
    htmlUrl: "https://github.com/AlistairBishop06/World-Generator-and-Explorer",
    stars: 0,
    forks: 0,
    updatedAt: "2026-04-22T16:18:43Z",
    pushedAt: "2026-04-22T16:18:24Z",
    size: 46,
    defaultBranch: "main",
    commitCount: 6
  },
  {
    name: "asynchronous-tower-building",
    fullName: "AlistairBishop06/asynchronous-tower-building",
    description: "An asynchronous tower building project.",
    language: "JavaScript",
    htmlUrl: "https://github.com/AlistairBishop06/asynchronous-tower-building",
    stars: 0,
    forks: 0,
    updatedAt: "2026-04-26T21:34:08Z",
    pushedAt: "2026-04-20T22:35:32Z",
    size: 1858,
    defaultBranch: "main",
    commitCount: 6
  },
  {
    name: "Silly-Sorting-Web-Game",
    fullName: "AlistairBishop06/Silly-Sorting-Web-Game",
    description: "A split-screen coding game about implementing absurd sorting rules in Python.",
    language: "TypeScript",
    htmlUrl: "https://github.com/AlistairBishop06/Silly-Sorting-Web-Game",
    stars: 0,
    forks: 0,
    updatedAt: "2026-04-16T16:33:48Z",
    pushedAt: "2026-04-16T16:33:45Z",
    size: 235,
    defaultBranch: "main",
    commitCount: 23
  },
  {
    name: "Kotlin-Weather-App",
    fullName: "AlistairBishop06/Kotlin-Weather-App",
    description: "A Kotlin weather app.",
    language: "Kotlin",
    htmlUrl: "https://github.com/AlistairBishop06/Kotlin-Weather-App",
    stars: 0,
    forks: 0,
    updatedAt: "2026-04-09T15:41:26Z",
    pushedAt: "2026-04-09T15:38:58Z",
    size: 7,
    defaultBranch: "main",
    commitCount: 2
  },
  {
    name: "youtube-card-game",
    fullName: "AlistairBishop06/youtube-card-game",
    description: "A JavaScript card game prototype.",
    language: "JavaScript",
    htmlUrl: "https://github.com/AlistairBishop06/youtube-card-game",
    stars: 0,
    forks: 0,
    updatedAt: "2026-04-05T23:46:09Z",
    pushedAt: "2026-04-05T23:46:02Z",
    size: 882,
    defaultBranch: "main",
    commitCount: 5
  },
  {
    name: "Lightweight-Ruby-Blog",
    fullName: "AlistairBishop06/Lightweight-Ruby-Blog",
    description: "A lightweight Ruby blog project.",
    language: "Ruby",
    htmlUrl: "https://github.com/AlistairBishop06/Lightweight-Ruby-Blog",
    stars: 0,
    forks: 0,
    updatedAt: "2026-04-05T19:41:50Z",
    pushedAt: "2026-04-05T19:41:21Z",
    size: 1,
    defaultBranch: "main",
    commitCount: 1
  },
  {
    name: "TeamProjectCOM2020",
    fullName: "AlistairBishop06/TeamProjectCOM2020",
    description: "Educational team project, not intended for commercial deployment.",
    language: "Python",
    htmlUrl: "https://github.com/AlistairBishop06/TeamProjectCOM2020",
    stars: 0,
    forks: 0,
    updatedAt: "2026-04-04T22:56:48Z",
    pushedAt: "2026-04-04T22:56:39Z",
    size: 93854,
    defaultBranch: "main",
    commitCount: 248
  },
  {
    name: "Net-Tool-Hub",
    fullName: "AlistairBishop06/Net-Tool-Hub",
    description: "A web hub for networking tools.",
    language: "HTML",
    htmlUrl: "https://github.com/AlistairBishop06/Net-Tool-Hub",
    stars: 0,
    forks: 0,
    updatedAt: "2026-04-04T21:43:42Z",
    pushedAt: "2026-04-04T21:43:39Z",
    size: 41,
    defaultBranch: "main",
    commitCount: 6
  },
  {
    name: "Optimised-Parking-Simulation",
    fullName: "AlistairBishop06/Optimised-Parking-Simulation",
    description: "A TypeScript parking simulation.",
    language: "TypeScript",
    htmlUrl: "https://github.com/AlistairBishop06/Optimised-Parking-Simulation",
    stars: 0,
    forks: 0,
    updatedAt: "2026-03-31T16:54:51Z",
    pushedAt: "2026-03-31T16:54:46Z",
    size: 95,
    defaultBranch: "main",
    commitCount: 2
  },
  {
    name: "Local-cheapest-fuel-map",
    fullName: "AlistairBishop06/Local-cheapest-fuel-map",
    description: "A FastAPI app for finding nearby fuel stations and cheapest fuel options.",
    language: "Python",
    htmlUrl: "https://github.com/AlistairBishop06/Local-cheapest-fuel-map",
    stars: 0,
    forks: 0,
    updatedAt: "2026-04-22T16:19:02Z",
    pushedAt: "2026-03-26T15:55:22Z",
    size: 12552,
    defaultBranch: "main",
    commitCount: 1
  },
  {
    name: "java-messageboard",
    fullName: "AlistairBishop06/java-messageboard",
    description: "A Java message board project.",
    language: "Java",
    htmlUrl: "https://github.com/AlistairBishop06/java-messageboard",
    stars: 0,
    forks: 0,
    updatedAt: "2026-03-25T19:11:40Z",
    pushedAt: "2026-03-25T19:11:36Z",
    size: 25,
    defaultBranch: "main",
    commitCount: 1
  },
  {
    name: "gamesleaguecw",
    fullName: "AlistairBishop06/gamesleaguecw",
    description: "A Java games league coursework project.",
    language: "Java",
    htmlUrl: "https://github.com/AlistairBishop06/gamesleaguecw",
    stars: 0,
    forks: 0,
    updatedAt: "2026-03-25T19:07:02Z",
    pushedAt: "2026-03-25T19:06:58Z",
    size: 744,
    defaultBranch: "main",
    commitCount: 1
  },
  {
    name: "battleships",
    fullName: "AlistairBishop06/battleships",
    description: "A Python web app implementation of the classic Battleships board game.",
    language: "Python",
    htmlUrl: "https://github.com/AlistairBishop06/battleships",
    stars: 0,
    forks: 0,
    updatedAt: "2026-03-25T18:34:08Z",
    pushedAt: "2026-03-25T18:34:04Z",
    size: 55,
    defaultBranch: "main",
    commitCount: 5
  },
  {
    name: "ai-mario",
    fullName: "AlistairBishop06/ai-mario",
    description: "A Lua AI Mario experiment.",
    language: "Lua",
    htmlUrl: "https://github.com/AlistairBishop06/ai-mario",
    stars: 0,
    forks: 0,
    updatedAt: "2026-03-22T18:34:26Z",
    pushedAt: "2026-03-22T18:34:22Z",
    size: 8,
    defaultBranch: "main",
    commitCount: 2
  },
  {
    name: "LIDAR",
    fullName: "AlistairBishop06/LIDAR",
    description: "A short horror game based on LIDAR scanning and loss of vision.",
    language: "ASP.NET",
    htmlUrl: "https://github.com/AlistairBishop06/LIDAR",
    stars: 0,
    forks: 0,
    updatedAt: "2026-03-22T18:32:11Z",
    pushedAt: "2026-03-22T18:32:08Z",
    size: 178428,
    defaultBranch: "main",
    commitCount: 3
  },
  {
    name: "AlistairBishop06",
    fullName: "AlistairBishop06/AlistairBishop06",
    description: "Profile README repository.",
    language: "Unknown",
    htmlUrl: "https://github.com/AlistairBishop06/AlistairBishop06",
    stars: 0,
    forks: 0,
    updatedAt: "2026-03-22T17:25:40Z",
    pushedAt: "2026-03-22T17:25:37Z",
    size: 9,
    defaultBranch: "main",
    commitCount: 5
  },
  {
    name: "MiniGameWebsite",
    fullName: "AlistairBishop06/MiniGameWebsite",
    description: "A PHP minigame website.",
    language: "PHP",
    htmlUrl: "https://github.com/AlistairBishop06/MiniGameWebsite",
    stars: 0,
    forks: 0,
    updatedAt: "2026-03-20T16:47:56Z",
    pushedAt: "2026-03-20T16:47:53Z",
    size: 10563,
    defaultBranch: "main",
    commitCount: 5
  },
  {
    name: "openmap-game",
    fullName: "AlistairBishop06/openmap-game",
    description: "A browser strategy prototype where players claim map buildings and generate resources.",
    language: "Python",
    htmlUrl: "https://github.com/AlistairBishop06/openmap-game",
    stars: 0,
    forks: 0,
    updatedAt: "2026-03-15T18:42:13Z",
    pushedAt: "2026-03-15T18:42:10Z",
    size: 1719,
    defaultBranch: "master",
    commitCount: 2
  },
  {
    name: "sports-mode",
    fullName: "AlistairBishop06/sports-mode",
    description: "A fullscreen sports dashboard for scores, fixtures, tables, and speedway results.",
    language: "HTML",
    htmlUrl: "https://github.com/AlistairBishop06/sports-mode",
    stars: 0,
    forks: 0,
    updatedAt: "2026-03-09T15:43:13Z",
    pushedAt: "2026-03-09T15:43:10Z",
    size: 44001,
    defaultBranch: "main",
    commitCount: 12
  },
  {
    name: "Python-Cloth-Sim",
    fullName: "AlistairBishop06/Python-Cloth-Sim",
    description: "A basic softbody cloth simulation built in Python with PyGame.",
    language: "Python",
    htmlUrl: "https://github.com/AlistairBishop06/Python-Cloth-Sim",
    stars: 0,
    forks: 0,
    updatedAt: "2026-03-08T13:51:06Z",
    pushedAt: "2026-03-08T13:51:03Z",
    size: 7,
    defaultBranch: "main",
    commitCount: 3
  },
  {
    name: "aifailuremuseumdeployment",
    fullName: "AlistairBishop06/aifailuremuseumdeployment",
    description: "AI failure museum deployment project.",
    language: "Python",
    htmlUrl: "https://github.com/AlistairBishop06/aifailuremuseumdeployment",
    stars: 0,
    forks: 0,
    updatedAt: "2026-03-02T14:17:23Z",
    pushedAt: "2026-03-02T14:15:34Z",
    size: 56129,
    defaultBranch: "main",
    commitCount: 1
  },
  {
    name: "Template-Space-Website",
    fullName: "AlistairBishop06/Template-Space-Website",
    description: "A basic website about past and future space travel.",
    language: "HTML",
    htmlUrl: "https://github.com/AlistairBishop06/Template-Space-Website",
    stars: 0,
    forks: 0,
    updatedAt: "2026-02-05T14:19:11Z",
    pushedAt: "2026-02-05T14:16:53Z",
    size: 7596,
    defaultBranch: "main",
    commitCount: 3
  },
  {
    name: "JavaCardGame-ECM2414",
    fullName: "AlistairBishop06/JavaCardGame-ECM2414",
    description: "A Java card game coursework project.",
    language: "Java",
    htmlUrl: "https://github.com/AlistairBishop06/JavaCardGame-ECM2414",
    stars: 0,
    forks: 0,
    updatedAt: "2026-01-24T14:23:48Z",
    pushedAt: "2025-10-29T13:30:07Z",
    size: 2777,
    defaultBranch: "main",
    commitCount: 7
  }
];
